hardware:
  device: 0
  compile: false
  coordinate_descent_tuning: true
  amp: true

resume_training:
  resume: false
  resume_directory: ../results/debug/b9584cfa25af4254a43d19ee6fa98a12

model:
  layer_swap:
    layer_name: SimpleCustomLinear # use original for default 
    copy_weights: true
    include_leaf_names: []   
    exclude_substrings: ["lm_head"]    
    replace_activations: none
    replace_norms: none                  
    default_custom_layer_config:
      alpha: 0.05
      # aux_loss_config:
      #   enabled: false
      #   weight: 1.0
      #   l1_activation: 0.0001

    per_layer_config:
      lm_head:
        alpha: 0.2
        # aux_loss_config:
        #   enabled: true
        #   weight: 1.0
        #   l1_activation: 0.001
  
  vocab_size: 50257
  n_layer: 12
  n_head: 12
  n_embed: 768


  # MODEL_CONFIGS = {
  #   "d12": GPTConfig(vocab_size=cfg['model']['vocab_size'], n_layer=12, n_head=12, n_embd=768),
  #   "d24": GPTConfig(vocab_size=cfg['model']['vocab_size'], n_layer=24, n_head=16, n_embd=1024),
  #   "d36": GPTConfig(vocab_size=cfg['model']['vocab_size'], n_layer=36, n_head=20, n_embd=1280),
  #   "d48": GPTConfig(vocab_size=cfg['model']['vocab_size'], n_layer=48, n_head=25, n_embd=1600),



training:
  batch_size: 16
  sequence_length: 2048
  num_iterations: 7168 #12288 #38146 # 800000 
  learning_rate: 0.005   
  warmup_iters: 2000
  warmdown_iters: 2028
  weight_decay: 0 #0.01
  grad_accumulation_steps: 16
  optimizer_betas: [0.9, 0.95] # Added optimizer betas
 
evaluation:
  val_tokens: 1048576  # Fixed value as per original code
  val_loss_every: 1024
  val_batch_size: 32

logging:
  output_dir: "../egor_log_results"
  save_every: 1024
  use_ml_flow: true #
  mlflow_tracking_uri: http://195.209.219.192:5000/
  experiment_name: activations_and_sparsity

data:
  input_bin: "data/fineweb10B/fineweb_train_*.bin"
  input_val_bin: "data/fineweb10B/fineweb_val_*.bin"
